from backend.agent_managers.feedback import FeedbackManager
from backend.agent_managers.pattern import PatternExtractor
from backend.agent_managers.git_merge import GitMergeAgent
from backend.agent_managers.orchestrator import AgentOrchestrator